name = input("Enter employee name: ")
department = input("Enter department: ")

print("\nEmployee Details")
print("----------------")
print("Name:", name)
print("Department:", department)
print("Application Version 3")
print("Feature: Health Check Enabled")
print("Updated from master and feature branch")
print("Application deployed from GitHub")
